dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "2.7"
      env: TOXENV=purepy27
      before_install:
        - sudo apt-get remove -y --allow-remove-essential gnupg gnupg2
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.8"
      env: TOXENV=purepy38
      before_install:
        - sudo apt-get remove -y  --allow-remove-essential gnupg gnupg2

before_install:
  - sudo apt-get update
  - sudo apt-get install -y swig

install:
  - pip install -U tox coveralls
  - wget https://dist.opendnssec.org/source/softhsm-2.3.0.tar.gz
  - tar -xzf softhsm-2.3.0.tar.gz
  - cd softhsm-2.3.0
  - sudo ./configure
  - sudo make
  - sudo make install

script:
  - tox

after_success:
  - coveralls
